### ISSUE TITLE
RESTful API: Is it possible to make an ".../account" GET request with a query that will return only contacts from a specific country?

### ISSUE THREAD

**Issue by javac9** [opencrx/opencrx-documentation#12]
I know that if one wants to get `Contact`s, the REST call should look like this:
`http://localhost:9090/opencrx-rest-CRX/org.opencrx.kernel.account1/provider/CRX/segment/Standard/account?queryType=org:opencrx:kernel:account1:Contact`

But what if the requirement is to only get those contacts that have a postal address with a specific country?

**Comment by javac9** [comment]
Would this be possible to achieve in a single request, or one should first obtain all contacts and then filter out manually the ones that have among their addresses a postal address with a specific country?

**Comment by wfro64** [comment]
Yes. Have a look at https://github.com/opencrx/opencrx/blob/master/core/src/test/java/org/opencrx/kernel/api/TestQuery.java test case testQueryPersonsHavingCountry

**Comment by javac9** [comment]
> Yes. Have a look at https://github.com/opencrx/opencrx/blob/master/core/src/test/java/org/opencrx/kernel/api/TestQuery.java test case testQueryPersonsHavingCountry

Thanks, I'll have a look. However, I experienced the problem using REST API - in the first post I put this URL which is supposed to fetch all `Contact`s:
`http://localhost:9090/opencrx-rest-CRX/org.opencrx.kernel.account1/provider/CRX/segment/Standard/account?queryType=org:opencrx:kernel:account1:Contact`

How does one then incorporate the `postalAddressQuery` subquery into the single URL?

**Comment by wfro64** [comment]
The easiest ways to construct / inspect REST requests are:
* Launch the "Explore API ..." wizard from the standard GUI on any object / inspector

OR

* If you have a client application log the REST interactions by a http proxy (e.g. `socat -v -t 1000 tcp4-listen:7180,reuseaddr,fork tcp4-connect:127.0.0.1:8080` or `grinder` do the job)
* Configure the client persistence manager to go through the proxy and use the mime type `application/json:`

		entityManagerFactory = org.opencrx.kernel.utils.Utils.getPersistenceManagerFactoryProxy(
			"http://127.0.0.1:7180/opencrx-rest-CRX/", // local proxy, e.g. Grinder
			"username", 
			"password*, 
			"application/json"
		);

For your case a simple GET does not work. You have to contruct a query object (as XML / JSON) and POST it as request body)

**Comment by javac9** [comment]
Thank you @wfro64 

I hate that I have to ask, but I don't have a clue how to construct such a complex query JSON object.

If I make the POST request work in Postman, I'll be able to recreate it in my Angular app (where I use REST API).
So in Postman, I put this in request body and did POST request (it didn't work of course - could not be parsed properly). Please give me some hints based on the following, even though it most likely is not even close to what I need:

```
{
    "@type": "org.opencrx.kernel.account1.cci2.ContactQuery",
    "thereExistsAddress": {
        "org.opencrx.kernel.account1.cci2.PostalAddressQuery": {
            "elementOf": {
                "@type": "org.opencrx.kernel.account1.cci2.PostalAddressQuery",
                "postalCountry: 240
            } 
        }
    }
}
```

**Comment by javac9** [comment]
Update:
I think this should be a lot closer to what one needs in order to get back only `Contact`s instead of all `Account`s

Request URL: `http://localhost:9090/opencrx-rest-CRX/org.opencrx.kernel.account1/provider/CRX/segment/Standard/account`

Query sent from the body of a POST request:
```
{
    "org.openmdx.kernel.QueryFilter": {
        "condition": [
            {
                "feature": "object_instanceof",
                "quantifier": 2,
                "type": 1,
                "value": [
                    "org:opencrx:kernel:account1:Contact"
                ]
            }
        ]
    }
}
```

This throws the following exception:
```

    "@type": "org.openmdx.kernel.Exception",
    "element": {
        "@exceptionDomain": "DefaultDomain",
        "@exceptionCode": "-23",
        "@exceptionClass": "java.lang.UnsupportedOperationException",
        "@methodName": "getOperation",
        "@lineNumber": "291",
        "description": "account",
        "parameter": null,
        "stackTraceElements": {
            "_item": [
                {
                    "@declaringClass": "org.openmdx.base.accessor.jmi.spi.FeatureMapper",
                    "@methodName": "getOperation",
                    "@fileName": "FeatureMapper.java",
                    "@lineNumber": "291"
                },
                {
                    "@declaringClass": "org.openmdx.base.accessor.jmi.spi.Jmi1ObjectInvocationHandler",
                    "@methodName": "invoke",
                    "@fileName": "Jmi1ObjectInvocationHandler.java",
                    "@lineNumber": "742"
                },
                {
                    "@declaringClass": "com.sun.proxy.$Proxy228",
                    "@methodName": "refInvokeOperation",
                    "@lineNumber": "-1"
                },
                {
                    "@declaringClass": "org.openmdx.application.rest.adapter.InboundConnection_2$InboundInteraction",
                    "@methodName": "invoke",
                    "@fileName": "InboundConnection_2.java",
                    "@lineNumber": "1318"
                },
                {
                    "@declaringClass": "org.openmdx.base.rest.spi.AbstractRestInteraction",
                    "@methodName": "handleOperation",
                    // MIDDLE PART REMOVED
                {
                    "@declaringClass": "java.util.concurrent.ThreadPoolExecutor$Worker",
                    "@methodName": "run",
                    "@fileName": "ThreadPoolExecutor.java",
                    "@lineNumber": "628"
                },
                {
                    "@declaringClass": "org.apache.tomcat.util.threads.TaskThread$WrappingRunnable",
                    "@methodName": "run",
                    "@fileName": "TaskThread.java",
                    "@lineNumber": "61"
                },
                {
                    "@declaringClass": "java.lang.Thread",
                    "@methodName": "run",
                    "@fileName": "Thread.java",
                    "@lineNumber": "834"
                }
            ]
        }
    }
}
```
