### ISSUE TITLE
JAVA API (opencrx-client-5.0.0): How to get all Products to which a particular Account was assigned?

### ISSUE THREAD

**Issue by javac9** [opencrx/opencrx-documentation#13]
I have created a `Product` and have assigned an existing `LegalEntity` as a supplier to it. Now, I'd like my `ProductService` to return this `Product` when I send the `Account` with the request.

I've been trying with the following code:
```
public List<Product> findAllForAccount(Account account, PersistenceManager pm) {
    ProductQuery productQuery = (ProductQuery) pm.newQuery(Product.class);
    productQuery.thereExistsAssignedAccount().equalTo(account);

    // one would expect a method that accepts the above productQuery as an argument
    // but it doesn't exist?
    // getSegment(pm).getProduct(productQuery)

    return getSegment(pm).getProduct()
            .stream()
            .map(Product.class::cast)
            .collect(Collectors.toList());
}
```
What am I missing here?

@wfro64

**Comment by DlRTY-HARRY** [comment]
1. I strongly recommend not to use the Java streaming API on openMDX collections at the moment as there are some issues waiting to be resolved.
2. If your `getSegment(pm)` method returned an instance of [org.opencrx.kernel.product1.jmi1.Segment](http://www.opencrx.org/opencrx/4.2/java/org/opencrx/kernel/product1/jmi1/Segment.html) then there would be a [`getProduct(ProductQuery query)`](http://www.opencrx.org/opencrx/4.2/java/org/opencrx/kernel/product1/jmi1/Segment.html#getProduct-org.opencrx.kernel.product1.cci2.ProductQuery-) method.

**Comment by DlRTY-HARRY** [comment]
### Regarding your query
Please have a look at the [Product Model](https://www.opencrx.org/opencrx/4.2/uml/opencrx-core/product1/tn/020_AbstractProduct.png.html): [`Account`](http://www.opencrx.org/opencrx/4.2/java/org/opencrx/kernel/account1/jmi1/Account.html)s are not assigned to [`Product`](http://www.opencrx.org/opencrx/4.2/java/org/opencrx/kernel/product1/jmi1/Product.html)s directly but through an [`AccountAssignmentProduct`](http://www.opencrx.org/opencrx/4.2/java/org/opencrx/kernel/product1/jmi1/AccountAssignmentProduct.html) entity specifying the assignment role!

Your query should therefore be written as `productQuery.thereExistsAssignedAccount().thereExistsAccount().equalTo(account);`

**or even more specific**

`
AccountAssignmentProductQuery accountAssignmentProductQuery = productQuery.thereExistsAssignedAccount();
accountAssignmentProductQuery.thereExistsAccount().equalTo(account);
accountAssignmentProductQuery.accountRole().equalTo(SUPPLIER_ROLE);
`

**Comment by wfro64** [comment]
Please have a look at the classes in package https://github.com/opencrx/opencrx/tree/master/core/src/test/java/org/opencrx. There you will find many examples. There is also an example for your specific case in https://github.com/opencrx/opencrx/blob/master/core/src/test/java/org/opencrx/kernel/api/TestQuery.java section "// Products with specific account assignment".
