### ISSUE TITLE
create an alias to latest UML Diagrams

### ISSUE THREAD

**Issue by brunoamacos** [opencrx/opencrx-documentation#48]
is it possible to create an alias to the latest UML-Diagrams. Like https://www.opencrx.org/opencrx/latest pointing to https://www.opencrx.org/opencrx/5.2 ?

It whould be very helpful when creating Documentations.

**Comment by wfro64** [comment]
https://www.opencrx.org/opencrx/latest/uml/opencrx-core/ points to latest models (https://www.opencrx.org/opencrx/5.3/uml/opencrx-core/)
