### ISSUE TITLE
link to docker image leads to nowhere

### ISSUE THREAD

**Issue by LUC4R4T0R** [opencrx/opencrx-documentation#49]
The linked page on docker hub in "How to install openCRX on Docker" does not exist (404).

Wiki page: [https://github.com/opencrx/opencrx-documentation/blob/master/Admin/InstallOnDocker.md](https://github.com/opencrx/opencrx-documentation/blob/master/Admin/InstallOnDocker.md)

Broken link: [https://hub.docker.com/r/opencrx/opencrx](https://hub.docker.com/r/opencrx/opencrx)

**Comment by wfro64** [comment]
Link is fixed. It now points to https://github.com/opencrx/opencrx-docker
